[package]
name = "orca-container"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "OverlayFS container runtime for orca"

[dependencies]
orca-image.workspace = true

libc.workspace = true
nix.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
