[package]
name = "orca"
version = "0.1.0"
authors = ["miyake13000 <https://github.com/miyake13000/orca>"]
edition = "2018"
description = "Container Runtime written by Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#fork = "0.1.18"
clap = "2.20.3"
