[package]
name = "orca"
version = "0.1.1"
authors = ["miyake13000 <https://github.com/miyake13000/orca>"]
edition = "2018"
description = "Container Runtime written by Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.22.0"
libc = "0.2"
clap = "2.20"
reqwest = { version = "0.10", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "3.0"
retry = "1.3.0"
tar = "0.4.37"
flate2 = "1.0.20"
