[package]
name = "orca-mount"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
license-file.workspace = true

[dependencies]
nix = { version = "0.30", features = ["mount"] }
anyhow = "1.0"
